### PR TITLE
Add linux aarch64 wheel support

### PR DESCRIPTION
**Pull request by odidev**
Added linux aarch64 wheel support.
Related to #53. @bstellato Could you please review this PR..

### CODE REVIEW

**Comment by odidev** [comment]
@bstellato, could you please review this PR? Thanks.

**Comment by odidev** [comment]
@bstellato, could you please review this PR? Thanks.

**Comment by odidev** [comment]
@bstellato, could you please have a look at this PR? Thanks in advance.

**Comment by odidev** [comment]
@bstellato, could you please have a look at this PR? Thanks in advance.

**Comment by odidev** [comment]
@bstellato, could you please have a look at this PR?

**Comment by odidev** [comment]
@vineetbansal, could you please review this PR? Thanks in advance.

**Comment by snadampal** [comment]
I'm curious why the commit been reverted? I couldn't find any detail in the revert commit message either.

**Pull request merged**
